package com.baidu.location;

import android.os.Environment;

interface ax {
    public static final int A = 54;
    public static final int B = 55;
    public static final int C = 51;
    public static final int D = 53;
    public static final int E = 13;
    public static final int F = 12000;
    public static final int G = 22;
    public static final int H = 65;
    public static final String I = (Environment.getExternalStorageDirectory().getPath() + "/baidu/tempdata");
    public static final int J = 207;
    public static final int K = 21;
    public static final int L = 1;
    public static final int M = 61;
    public static final int N = 64;
    public static final int O = 5120;
    public static final int P = 205;
    public static final int Q = 11;
    public static final int b = 204;
    public static final int byte = 1;
    public static final int c = 209;
    public static final int case = 43;
    public static final int char = 26;
    public static final int d = 0;
    public static final int do = 25;
    public static final int e = 42;
    public static final int else = 12;
    public static final int f = 52;
    public static final int for = 2;
    public static final int g = 110;
    public static final int goto = 14;
    public static final int h = 31;
    public static final String i = "baidu_location_service";
    public static final int if = 203;
    public static final int int = 111;
    public static final int j = 206;
    public static final int k = 3;
    public static final int l = 101;
    public static final int long = 202;
    public static final int m = 57;
    public static final int n = 28;
    public static final int new = 208;
    public static final int o = 23;
    public static final int p = 27;
    public static final int q = 15;
    public static final int r = 4;
    public static final int s = 63;
    public static final int t = 201;
    public static final int try = 92;
    public static final int u = 62;
    public static final int v = 91;
    public static final int void = 24;
    public static final int w = 71;
    public static final int x = 41;
    public static final int y = 81;
    public static final int z = 56;
}
